server:
  port: 5173
  debug: false

datasource:
  default:
    driver: "mysql"
    host: "localhost"
    port: 3306
    database: "data_lake_ui_app"
    username: "root"
    password: "root"
    charset: "utf8"
    loc: "Local"
  ds2:
    driver: "postgres"
    host: "localhost"
    port: 5432
    database: "data_lake_ui_app"
    username: "root"
    password: "root"
    sslmode: "disable"
    timezone: ""

redis:
  host: "localhost:6379"
  password: "root"
  db: 0

logger:
  console:
    level: "info"
    driver: "console"
  file:
    level: "info"
    driver: "file"
    filename: "./log/data_lake_ui_app.log"
    maxsize: 10
    maxbackups: 2
    maxage: 27
    compress: true
