server:
  port: 22000
  debug: false

xrd:
  host: "localhost"
  port: 1094
  initial_dir: "/tmp"
  xrd_client_bin_path: "/opt/homebrew/bin/"
  # in seconds
  process_timeout: 60
  staging_path: "/tmp/delete_me"
  staging_tmp_dir_prefix: "stg_"
  # in minutes
  sanitation_job_interval: 30

logger:
  console:
    level: "info"
    driver: "console"
  file:
    level: "info"
    driver: "file"
    filename: "./log/data_lake_ui_app.log"
    maxsize: 10
    maxbackups: 2
    maxage: 27
    compress: true
