#!/bin/sh
set -e

# Certificate paths
CERT_DIR="/etc/nginx/ssl"
SHARED_CERT_DIR="/etc/shared-certs"
CERT_FILE="$SHARED_CERT_DIR/server.crt"
KEY_FILE="$SHARED_CERT_DIR/server.key"

# Create directories
mkdir -p "$CERT_DIR"

# Certificates should already exist (generated by cert-init service)
# Just verify and copy them to nginx's directory
if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
    echo "ERROR: SSL certificates not found in $SHARED_CERT_DIR"
    echo "The cert-init service should have generated them."
    exit 1
fi

# Check if certificates exist in the shared volume
if [ -f "$SHARED_CERT_DIR/hostcert.pem" ] && [ -f "$SHARED_CERT_DIR/hostkey.pem" ]; then
    echo "[+] SSL certificates found in $SHARED_CERT_DIR"

# Copy to nginx's own directory for convenience
cp "$CERT_FILE" "$CERT_DIR/server.crt"
cp "$KEY_FILE" "$CERT_DIR/server.key"

# Set proper permissions
    chmod 644 "$CERT_DIR/hostcert.pem"
    chmod 600 "$CERT_DIR/hostkey.pem"
    
    echo "[+] Certificates ready for nginx"
    ls -la "$CERT_DIR/"
else# Chain to nginx's original entrypoint, then execute CMD
exec /docker-entrypoint.sh "$@"
