# A podman container
#
# Build stage
FROM golang:latest as build-stage

# Install XRootD client tools
RUN apt-get update && apt-get install -y xrootd-client && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ./ .

# Install dependencies
RUN go mod download

# build app for production
RUN go build -o /dataharbor_backend

#EXPOSE 22000
CMD [ "/dataharbor_backend" ]