name: Frontend
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: '1.22'
      - name: Build
        working-directory: ./app
        run: go build -v ./...

# - name: Test
#   run: go test -v ./...
