# A podman container
# build: podman build -t data_lake_ui .
# run: podman run -p 8080:8080 data_lake_ui
# Use the official Node.js image as the base image
FROM node:latest as build-stage

WORKDIR /web

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ./ .

# Install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# build app for production with minification
RUN npm run build

# Production stage
FROM nginx:1.19.0-alpine as production-stage
# Copy the build application from the previous stage to the Nginx container
COPY --from=build-stage /web/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
ENTRYPOINT ["nginx", "-g", "daemon off;"]