# nginx.conf
server {
    listen 80;
    server_name data-lake-ui;

    root /usr/share/data-lake-ui-frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        alias /usr/share/data-lake-ui-frontend/assets/;
        expires max;
        access_log off;
        add_header Cache-Control "public";
    }

    error_log /var/log/nginx/data-lake-ui-frontend-error.log;
    access_log /var/log/nginx/data-lake-ui-frontend-access.log;
}
